version: '3'
## each brower run separe port to finish test ( now if use port 4444 hub cannot finish test
services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"  # Chrome standalone port
      - "7900:7900"  # noVNC port for Chrome (optional)
    shm_size: "2g"   # Shared memory for Chrome
    environment:
      - SE_NODE_MAX_SESSIONS=5  # Maximum number of concurrent sessions
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - selenium-network


networks:
  selenium-network:
    driver: bridge