version: '3.8'

services:
  jenkins:
    image: trion/jenkins-docker-client
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_USER=1000
      - JENKINS_CAC=true
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_LOCATION=http://localhost:8080
      - JENKINS_CASC=/provisioning/jenkins-casc.yaml
    volumes:
      - /Users/mac/Documents/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-casc.yaml:/provisioning/jenkins-casc.yaml
      - ./plugins.txt:/provisioning/plugins.txt
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: root
    networks:
      - jenkins-net  # Connect to the custom network

  selenium:
    image: selenium/standalone-chrome:115.0.5790.110
    container_name: selenium
    ports:
      - "4444:4444"
    networks:
      - jenkins-net  # Connect to the custom network

networks:
  jenkins-net:  # Declare the custom network
    driver: bridge
