pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                dir('selenium-java-automation') {
                   // bat 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir('selenium-java-automation') {
                    bat 'mvn test'
                }
            }
        }
    }
}
