version: '3.8'
services:
  jenkins:
    image: trion/jenkins-docker-client
    container_name: jenkins
    #share ram
    shm_size: 2gb
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_USER=1000
      - JENKINS_CAC=true
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JENKINS_LOCATION=http://localhost:8080
      - JENKINS_CASC=/provisioning/jenkins-casc.yaml
    volumes:
      - /Users/mac/Documents/jenkins:/var/jenkins_home
      #https://dev.to/piyushbagani15/understanding-varrundockersock-the-key-to-dockers-inner-workings-nm7
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-casc.yaml:/provisioning/jenkins-casc.yaml
      - ./plugins.txt:/provisioning/plugins.txt
    privileged: true
    # communication with the host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: root
